site_name: specification
docs_dir: "specification"

nav:
  - Introduction: "README.md"
  - Protocol:
      - Overview: "protocol/README.md"
      - Protocol Changes: "protocol/protocol-changes.md"
      - Accounts: "protocol/accounts.md"
      - Ledger: "protocol/ledger.md"
      - Smart Contracts: "protocol/smart-contracts.md"
      - Supply: "protocol/supply.md"
      - Time: "protocol/time.md"
      - Wallets: "protocol/wallets.md"
      - Forks: "protocol/forks.md"
      - Coin Distribution: "protocol/distribution.md"
      - Consensus:
          - Delegates: "protocol/consensus/delegates.md"
          - "Delegated Proof of Importance": "protocol/consensus/dpoi.md"
      - Transactions:
          - Blocks: "protocol/transactions/blocks.md"
          - Fees: "protocol/transactions/fees.md"
      - Networking:
          - Peering: "protocol/networking/peering.md"
          - Voting: "protocol/networking/voting.md"
  - Glossary: "glossary.md"
  - Styleguide: "styleguide.md"
  - Whitepaper: "whitepaper/README.md"
