site_name: Specification
docs_dir: "specification"

nav:
  - Introduction: "README.md"
  # - Whitepaper: "whitepaper/README.md"
  - Protocol:
      - Overview: "protocol/README.md"
      - Supply: "protocol/supply.md"
      - Coin Distribution: "protocol/distribution.md"
      - Consensus: "protocol/consensus.md"
      - Transactions:
          - Fees: "protocol/transactions/fees.md"
